feat: Changelog 6.0.0
applicaster/zapp-platform-android pull request #135
Opened 2021-06-16 20:59 UTC by inckie

### Detailed readable description

Changelog 6.0.0

### Checklist
- [ ] I've provided a readable title for the PR
- [ ] I've provided a detailed description
- [ ] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

### UI changes
> Check one of the following checkboxes
- [ ] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

#### PR type
> check one of the following type and make sure all related checkboxes are checked.
- [ ] My PR is a part of a new feature or a feature improvement
    - [ ] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [ ] My PR is a bug fix
    - [ ] I provided a link in the description to the relevant Jira ticket  or provided the following in the PR description:
        - steps to reproduce a bug
        - expected result

### Having problem filling out the checklist / Conforming to guidelines - explain why and consult Zapp tech lead / Head of product

2021-06-17 13:05 UTC, ranmeirman requested changes
tiny comment

2021-06-17 13:05 UTC, ranmeirman commented on CHANGELOG.md
> + - Removed moment dependency to reduce bundle size
Can you change here to "moment.js" with quotes?

2021-06-17 13:42 UTC, inckie commented on CHANGELOG.md
> + - Removed moment dependency to reduce bundle size
done

2021-06-18 13:31 UTC, ranmeirman approved these changes

2021-06-18 15:18 UTC, merged