feat: upload release bundle file (aab) to S3
applicaster/zapp-platform-android pull request #162
Opened 2021-09-17 19:08 UTC by inckie

### Detailed readable description

- upload release bundle file (aab) to S3 and notify Zapp

### Checklist
- [ ] I've provided a readable title for the PR
- [ ] I've provided a detailed description
- [ ] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

### UI changes
> Check one of the following checkboxes
- [ ] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

#### PR type
> check one of the following type and make sure all related checkboxes are checked.
- [ ] My PR is a part of a new feature or a feature improvement
    - [ ] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [ ] My PR is a bug fix
    - [ ] I provided a link in the description to the relevant Jira ticket  or provided the following in the PR description:
        - steps to reproduce a bug
        - expected result

### Having problem filling out the checklist / Conforming to guidelines - explain why and consult Zapp tech lead / Head of product

2022-04-04 20:50 UTC, ranmeirman requested changes

2022-04-04 20:50 UTC, ranmeirman commented on rake/tasks/notify_zapp.rake
> +    :bundle_install_url,
we probably don't need this - it will be useless because we cannot install the app on device.

2022-04-04 20:50 UTC, ranmeirman commented on rake/tasks/notify_zapp.rake
> +    :bundle_appcenter_release_id,
do we need this appcenter values? I don't think so

2022-04-04 20:59 UTC, inckie commented on rake/tasks/notify_zapp.rake
> +    :bundle_appcenter_release_id,
Yes, I'll remove it

2022-04-05 19:20 UTC, ranmeirman requested changes

2022-04-05 19:20 UTC, ranmeirman commented on rake/tasks/notify_zapp.rake
> +      bundle_download_link: args[:bundleartifact_download_url],
you have a typo here.
Also please change to `release_bundle_download_url`, at the moment we only do release.

2022-04-06 21:54 UTC, ranmeirman approved these changes
Let's make sure we remove the extra build right after.

2022-04-06 23:11 UTC, merged