chore: changelog for SDK 9.0.0
applicaster/zapp-platform-android pull request #226
Opened 2022-08-02 19:07 UTC by inckie

### Detailed readable description

Changelog for SDK 9.0.0

### Checklist
- [ ] I've provided a readable title for the PR
- [ ] I've provided a detailed description
- [ ] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

### UI changes
> Check one of the following checkboxes
- [ ] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

#### PR type
> check one of the following type and make sure all related checkboxes are checked.
- [ ] My PR is a part of a new feature or a feature improvement
    - [ ] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [ ] My PR is a bug fix
    - [ ] I provided a link in the description to the relevant Jira ticket  or provided the following in the PR description:
        - steps to reproduce a bug
        - expected result

### Having problem filling out the checklist / Conforming to guidelines - explain why and consult Zapp tech lead / Head of product

2022-08-04 20:53 UTC, ranmeirman requested changes

2022-08-04 20:53 UTC, ranmeirman commented on CHANGELOG.md
> +- Advertising Id collection moved to plugin to comply with new Google Play requirements [#1510](https://github.com/applicaster/applicaster-android-sdk/pull/1510)
Let's move to breaking changes. I would also remove completely the sdk separation, the reader does not really care if it is sdk or platform

2022-08-04 20:53 UTC, ranmeirman commented on CHANGELOG.md
> +## 9.0.0 (January 26, 2022)
Date is wrong, it's August:)

2022-08-04 21:57 UTC, inckie commented on CHANGELOG.md
> +## 9.0.0 (January 26, 2022)
Indeed, fixed

2022-08-04 21:57 UTC, inckie commented on CHANGELOG.md
> +- Advertising Id collection moved to plugin to comply with new Google Play requirements [#1510](https://github.com/applicaster/applicaster-android-sdk/pull/1510)
Moved and merged sections

2022-08-05 15:19 UTC, ranmeirman approved these changes

2022-08-05 15:19 UTC, merged