Feat: polish preloader
applicaster/zapp-platform-android pull request #67
Opened 2020-09-28 19:03 UTC by inckie

Just shave off some code.

### Checklist
- [ ] I've provided a readable title for the PR
- [ ] I've provided a detailed description
- [ ] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

### UI changes
> Check one of the following checkboxes
- [ ] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

#### PR type
> check one of the following type and make sure all related checkboxes are checked.
- [ ] My PR is a part of a new feature or a feature improvement
    - [ ] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [ ] My PR is a bug fix
    - [ ] I provided a link in the description to the relevant Jira ticket  or provided the following in the PR description:
        - steps to reproduce a bug
        - expected result

### Having problem filling out the checklist / Conforming to guidelines - explain why and consult Zapp tech lead / Head of product

2020-11-25 21:20 UTC, ranmeirman requested changes
I think you should add tests to the different sequences.

2020-11-25 21:20 UTC, ranmeirman commented on android_quickbrick_app/src/main/java/com/applicaster/ui/loaders/PreloadStateManager.kt
> +        VIDEO_INTRO,
not always we have video intro, sometimes will only be image

2020-11-25 21:28 UTC, inckie commented on android_quickbrick_app/src/main/java/com/applicaster/ui/loaders/PreloadStateManager.kt
> +        VIDEO_INTRO,
if its just image, it will complete right away,  so lets assume it means video 0s length

2020-11-25 21:38 UTC, inckie commented
> I think you should add tests to the different sequences.

Its too hard, we need to actually run app, since most of the work is happens somewhere outside in the callbacks, and if something will fail or deadlock, it will be due to internal implementation of these callbacks we call here. And there are not real sequence, we have one linear with 4 steps hooks->load data->hooks->prepare ui, and video on the background all the time. When both completes, we present

2020-12-01 16:52 UTC, ranmeirman approved these changes

2020-12-01 18:32 UTC, merged